### ISSUE TITLE
In wizard lijkt het toevoegen van 'Kies een zoekfunctie' niet tot een zoekbalk

### ISSUE THREAD

**Issue by rduivenvoorde** [geo-frontend/nlmaps#21]
In de huidige versie van de wizard:

https://nlmaps.nl/#wizard

lijkt het gebruik van een 'Zoekbalk' niet te leiden tot een zoekbalk. Ook niet wanneer je de javascript in een html pagina plakt.

Wel zie je de property search: true verschijnen in de opts.

of mis ik iets?

**Comment by geppyz** [comment]
Dit probleem is inmiddels opgelost.
