### ISSUE TITLE
Nlmaps geeft naast percelen ook géén gebouwen weer.

### ISSUE THREAD

**Issue by Jammerdan** [geo-frontend/nlmaps#47]
NLmaps lijkt niet aan te sluiten op DKK v4.
Gebouwen en percelen worden dan ook niet meer weergegeven.
(https://geoforum.nl/t/nl-maps-geeft-geen-percelen-meer-weer/4403/2)

**Comment by emacgillavry** [comment]
Zojuist is de nieuwe code gemergd (zie https://github.com/geo-frontend/nlmaps/pull/62), waarmee deze problemen verholpen zijn.

**Comment by Jammerdan** [comment]
Check!
Werkt perfect Edward.
Thnx!!
