### ISSUE TITLE
Cerificate issue op nlmaps.nl

### ISSUE THREAD

**Issue by nlsvgtr** [geo-frontend/nlmaps#78]
Ik had het onderstaande vorige week gemaild aan de adressen die ik in SIDN WhoIs vond, maar daarop wordt niet gereageerd. Wellicht dat ik hier iemand bereik die er over gaat. Zo niet, dan excuses voor overlast.

De issue: op https://nlmaps.nl geeft Firefox een error 'SEC_ERROR_REVOKED_CERTIFICATE'. IE schijnt ook niet te werken.
Chrome doet het gek genoeg wel.

Dat is onder meer vervelend als je de nlmaps code van die site haalt (https://nlmaps.nl/dist/nlmaps.iife.js).

**Comment by nlsvgtr** [comment]
Na dagen blijkbaar alsnog door iemand opgepakt. Ik sluit dit issue.

**Comment by jeroenPDOK** [comment]
@nlsvgtr we zijn hier gisteren en vandaag mee bezig geweest maar hebben in de drukte vergeten te reageren. Het goede nieuws is dat het is opgelost.
